### ISSUE TITLE
Unable to Configure MinUpgradeFormatScore in sonarr_quality_profile Module

### ISSUE THREAD

**Issue by gsymeoni** [devopsarr/ansible-collection-sonarr#86]
### Issue Description:

The Sonarr API for creating a quality profile differentiates between two fields:

- `MinFormatScore`
- `MinUpgradeFormatScore`

The module `devopsarr.sonarr.sonarr_quality_profile` exposes a parameter `min_format_score`, which maps to the Sonarr API's `MinFormatScore`. However, the API's `MinUpgradeFormatScore` field is not exposed by the module, and defaults to 0, which is not a valid value according to the Sonarr API validation. This leads to errors when creating a quality profile.

```json
"'Min Upgrade Format Score' must be greater than or equal to '1'."
```

### Steps to Reproduce

1. Use the `sonarr_quality_profile` module:

    ```yaml
    - name: Create Quality Profile
      devopsarr.sonarr.sonarr_quality_profile:
        sonarr_url: "http://your-sonarr-url"
        sonarr_api_key: "your-api-key"
        name: "Example Profile"
        min_format_score: 5
        # other required parameters...
    ```

2. Attempt to create the quality profile.

3. Observe the error about `MinUpgradeFormatScore` needing to be at least 1

### Environment
- Ansible: 2.17.7
- Sonarr: 4.0.12.2823
- Collection: 1.2.0
- Sonarr-py: 1.0.2
