### ISSUE TITLE
Ordering all qualities (disabled or enabled)

### ISSUE THREAD

**Issue by RomLecat** [devopsarr/ansible-collection-sonarr#90]
Hi !

As discussed in #69, a way to order qualities, even the one disabled, would be nice.
This is because Sonarr (and Radarr) do evaluate disabled qualities when deciding if it should download a new release and overwrite existing files.

For instance, if WEBDL-2160p (disabled) is rated above WEBDL-1080p (enabled) and the files on the disk are WEBDL-2160p, Sonarr will not download WEBDL-1080p releases.
If WEBDL-1080p (enabled) is above WEBDL-2160p (disabled, on disk), Sonarr will download WEBDL-1080p release and replace WEBDL-2160p files on disk.

There's currently no way of moving disabled qualities.

Thanks!

**Comment by Fuochi** [comment]
Hi @RomLecat, sorry closed this by mistake, v1.3.1 should be out soon. could you please check if it solve this issue?
I tried this:
```yaml
 - devopsarr.sonarr.sonarr_quality_profile:
    name: Example
    upgrade_allowed: false
    cutoff: 1
    min_format_score: 0
    cutoff_format_score: 0
    quality_groups:
      - qualities:
          - id: 1
            name: SDTV
            source: television
            resolution: 480
      - allowed: false
        qualities:
          - id: 4
            name: HDTV-720p
            source: television
            resolution: 720
      - allowed: false
        name: WEB 480p
        id: 1002
        qualities:
          - id: 12
            name: WEBRip-480p
            source: webRip
            resolution: 480
          - id: 8
            name: WEBDL-480p
            source: web
            resolution: 480
      - name: WEB 720p
        id: 1001
        qualities:
          - id: 14
            name: WEBRip-720p
            source: webRip
            resolution: 720
          - id: 5
            name: WEBDL-720p
            source: web
            resolution: 720
    formats:
      - name: "{{ format['name'] }}"
        id: "{{ format['id'] }}"
        score: 100
    sonarr_api_key: "{{ sonarr_api_key }}"
    sonarr_url: "{{ sonarr_url }}"
```
If you specify `allowed: false` on the quality group, it will add it as not allowed. if you don't fill in the field, it should behave in the same way as before. Similarly, all the missing qualities will be added in queue as not allowed.

**Comment by RomLecat** [comment]
It seems to work fine, thanks!
I still wish we could reference qualities, custom profiles and quality groups by name instead of the whole:

```yaml
- id: 14
  name: WEBRip-720p
  source: webRip
  resolution: 720
```
It would make it a whole easier.

In the meantime I did this:
```yaml
- name: Setup 1080p quality profile
  devopsarr.sonarr.sonarr_quality_profile:
    name: "1080p"
    upgrade_allowed: true
    cutoff: "{{ bluray_1080p.id }}"
    min_format_score: 0
    cutoff_format_score: 100000
    quality_groups:
      - allowed: false
        qualities:
          - "{{ hdtv_720p }}"
      - name: "WEB 1080p"
        id: 1000
        qualities:
          - "{{ webrip_1080p }}"
          - "{{ webdl_1080p }}"
      - qualities:
          - "{{ bluray_1080p }}"
      - name: "WEB 2160p"
        id: 1001
        allowed: false
        qualities:
          - "{{ webrip_2160p }}"
          - "{{ webdl_2160p }}"
    sonarr_url: "{{ sonarr_instance.url }}"
    sonarr_api_key: "{{ sonarr_instance.api_key }}"
  vars:
    qualities: "{{ sonarr_qualities
                    | json_query('qualities[].quality')
                }}"
    custom_formats: "{{ sonarr_cf
                          | json_query('custom_formats[].{id: id, name: name}')
                      }}"
    webdl_2160p: "{{ qualities | json_query('[?name==`WEBDL-2160p`] | [0]') }}"
    webrip_2160p: "{{ qualities | json_query('[?name==`WEBRip-2160p`] | [0]') }}"
    bluray_1080p: "{{ qualities | json_query('[?name==`Bluray-1080p`] | [0]') }}"
    webdl_1080p: "{{ qualities | json_query('[?name==`WEBDL-1080p`] | [0]') }}"
    webrip_1080p: "{{ qualities | json_query('[?name==`WEBRip-1080p`] | [0]') }}"
    hdtv_1080p: "{{ qualities | json_query('[?name==`HDTV-1080p`] | [0]') }}"
    bluray_720p: "{{ qualities | json_query('[?name==`Bluray-720p`] | [0]') }}"
    webdl_720p: "{{ qualities | json_query('[?name==`WEBDL-720p`] | [0]') }}"
    webrip_720p: "{{ qualities | json_query('[?name==`WEBRip-720p`] | [0]') }}"
    hdtv_720p: "{{ qualities | json_query('[?name==`HDTV-720p`] | [0]') }}"
```

Thanks!
